### ISSUE TITLE
product.html:62-63: Resurrect product.diameter_out field...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#407] opened 2019-01-25 12:39 UTC
The puzzle `SE432-bb2f9735` from #SE432 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/4a4a83794ebfa4565f0bf7613b010c94cc624b54/templates/catalog/product.html#L62-L63

The puzzle was created by @duker33 on 25-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment] 2019-01-25 12:39
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment] 2019-01-25 12:42
duplicate of #403

**Closed** 2019-01-25 12:42 UTC
